[project]
title = "Citizen Science"
copyright = "2024 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://citizen-science.lsst.io"
github_url = "https://github.com/lsst/citizen-science"
version = "Current"
